/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kinsaleins.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class POCEntity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1489902514485248267L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"POCEntity\",\"namespace\":\"com.kinsaleins.avro\",\"fields\":[{\"name\":\"idt_enterprise_txn_entity\",\"type\":\"string\"},{\"name\":\"num_enterprise_txn_entity_edition\",\"type\":\"int\"},{\"name\":\"num_enterprise_txn_entity_version\",\"type\":\"int\"},{\"name\":\"dte_event_occurred\",\"type\":\"string\"},{\"name\":\"nme_creator\",\"type\":\"string\"},{\"name\":\"nme_event_type\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<POCEntity> ENCODER =
      new BinaryMessageEncoder<POCEntity>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<POCEntity> DECODER =
      new BinaryMessageDecoder<POCEntity>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<POCEntity> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<POCEntity> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<POCEntity> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<POCEntity>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this POCEntity to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a POCEntity from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a POCEntity instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static POCEntity fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence idt_enterprise_txn_entity;
  private int num_enterprise_txn_entity_edition;
  private int num_enterprise_txn_entity_version;
  private java.lang.CharSequence dte_event_occurred;
  private java.lang.CharSequence nme_creator;
  private java.lang.CharSequence nme_event_type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public POCEntity() {}

  /**
   * All-args constructor.
   * @param idt_enterprise_txn_entity The new value for idt_enterprise_txn_entity
   * @param num_enterprise_txn_entity_edition The new value for num_enterprise_txn_entity_edition
   * @param num_enterprise_txn_entity_version The new value for num_enterprise_txn_entity_version
   * @param dte_event_occurred The new value for dte_event_occurred
   * @param nme_creator The new value for nme_creator
   * @param nme_event_type The new value for nme_event_type
   */
  public POCEntity(java.lang.CharSequence idt_enterprise_txn_entity, java.lang.Integer num_enterprise_txn_entity_edition, java.lang.Integer num_enterprise_txn_entity_version, java.lang.CharSequence dte_event_occurred, java.lang.CharSequence nme_creator, java.lang.CharSequence nme_event_type) {
    this.idt_enterprise_txn_entity = idt_enterprise_txn_entity;
    this.num_enterprise_txn_entity_edition = num_enterprise_txn_entity_edition;
    this.num_enterprise_txn_entity_version = num_enterprise_txn_entity_version;
    this.dte_event_occurred = dte_event_occurred;
    this.nme_creator = nme_creator;
    this.nme_event_type = nme_event_type;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idt_enterprise_txn_entity;
    case 1: return num_enterprise_txn_entity_edition;
    case 2: return num_enterprise_txn_entity_version;
    case 3: return dte_event_occurred;
    case 4: return nme_creator;
    case 5: return nme_event_type;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idt_enterprise_txn_entity = (java.lang.CharSequence)value$; break;
    case 1: num_enterprise_txn_entity_edition = (java.lang.Integer)value$; break;
    case 2: num_enterprise_txn_entity_version = (java.lang.Integer)value$; break;
    case 3: dte_event_occurred = (java.lang.CharSequence)value$; break;
    case 4: nme_creator = (java.lang.CharSequence)value$; break;
    case 5: nme_event_type = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idt_enterprise_txn_entity' field.
   * @return The value of the 'idt_enterprise_txn_entity' field.
   */
  public java.lang.CharSequence getIdtEnterpriseTxnEntity() {
    return idt_enterprise_txn_entity;
  }


  /**
   * Sets the value of the 'idt_enterprise_txn_entity' field.
   * @param value the value to set.
   */
  public void setIdtEnterpriseTxnEntity(java.lang.CharSequence value) {
    this.idt_enterprise_txn_entity = value;
  }

  /**
   * Gets the value of the 'num_enterprise_txn_entity_edition' field.
   * @return The value of the 'num_enterprise_txn_entity_edition' field.
   */
  public int getNumEnterpriseTxnEntityEdition() {
    return num_enterprise_txn_entity_edition;
  }


  /**
   * Sets the value of the 'num_enterprise_txn_entity_edition' field.
   * @param value the value to set.
   */
  public void setNumEnterpriseTxnEntityEdition(int value) {
    this.num_enterprise_txn_entity_edition = value;
  }

  /**
   * Gets the value of the 'num_enterprise_txn_entity_version' field.
   * @return The value of the 'num_enterprise_txn_entity_version' field.
   */
  public int getNumEnterpriseTxnEntityVersion() {
    return num_enterprise_txn_entity_version;
  }


  /**
   * Sets the value of the 'num_enterprise_txn_entity_version' field.
   * @param value the value to set.
   */
  public void setNumEnterpriseTxnEntityVersion(int value) {
    this.num_enterprise_txn_entity_version = value;
  }

  /**
   * Gets the value of the 'dte_event_occurred' field.
   * @return The value of the 'dte_event_occurred' field.
   */
  public java.lang.CharSequence getDteEventOccurred() {
    return dte_event_occurred;
  }


  /**
   * Sets the value of the 'dte_event_occurred' field.
   * @param value the value to set.
   */
  public void setDteEventOccurred(java.lang.CharSequence value) {
    this.dte_event_occurred = value;
  }

  /**
   * Gets the value of the 'nme_creator' field.
   * @return The value of the 'nme_creator' field.
   */
  public java.lang.CharSequence getNmeCreator() {
    return nme_creator;
  }


  /**
   * Sets the value of the 'nme_creator' field.
   * @param value the value to set.
   */
  public void setNmeCreator(java.lang.CharSequence value) {
    this.nme_creator = value;
  }

  /**
   * Gets the value of the 'nme_event_type' field.
   * @return The value of the 'nme_event_type' field.
   */
  public java.lang.CharSequence getNmeEventType() {
    return nme_event_type;
  }


  /**
   * Sets the value of the 'nme_event_type' field.
   * @param value the value to set.
   */
  public void setNmeEventType(java.lang.CharSequence value) {
    this.nme_event_type = value;
  }

  /**
   * Creates a new POCEntity RecordBuilder.
   * @return A new POCEntity RecordBuilder
   */
  public static com.kinsaleins.avro.POCEntity.Builder newBuilder() {
    return new com.kinsaleins.avro.POCEntity.Builder();
  }

  /**
   * Creates a new POCEntity RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new POCEntity RecordBuilder
   */
  public static com.kinsaleins.avro.POCEntity.Builder newBuilder(com.kinsaleins.avro.POCEntity.Builder other) {
    if (other == null) {
      return new com.kinsaleins.avro.POCEntity.Builder();
    } else {
      return new com.kinsaleins.avro.POCEntity.Builder(other);
    }
  }

  /**
   * Creates a new POCEntity RecordBuilder by copying an existing POCEntity instance.
   * @param other The existing instance to copy.
   * @return A new POCEntity RecordBuilder
   */
  public static com.kinsaleins.avro.POCEntity.Builder newBuilder(com.kinsaleins.avro.POCEntity other) {
    if (other == null) {
      return new com.kinsaleins.avro.POCEntity.Builder();
    } else {
      return new com.kinsaleins.avro.POCEntity.Builder(other);
    }
  }

  /**
   * RecordBuilder for POCEntity instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<POCEntity>
    implements org.apache.avro.data.RecordBuilder<POCEntity> {

    private java.lang.CharSequence idt_enterprise_txn_entity;
    private int num_enterprise_txn_entity_edition;
    private int num_enterprise_txn_entity_version;
    private java.lang.CharSequence dte_event_occurred;
    private java.lang.CharSequence nme_creator;
    private java.lang.CharSequence nme_event_type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kinsaleins.avro.POCEntity.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idt_enterprise_txn_entity)) {
        this.idt_enterprise_txn_entity = data().deepCopy(fields()[0].schema(), other.idt_enterprise_txn_entity);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.num_enterprise_txn_entity_edition)) {
        this.num_enterprise_txn_entity_edition = data().deepCopy(fields()[1].schema(), other.num_enterprise_txn_entity_edition);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.num_enterprise_txn_entity_version)) {
        this.num_enterprise_txn_entity_version = data().deepCopy(fields()[2].schema(), other.num_enterprise_txn_entity_version);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.dte_event_occurred)) {
        this.dte_event_occurred = data().deepCopy(fields()[3].schema(), other.dte_event_occurred);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.nme_creator)) {
        this.nme_creator = data().deepCopy(fields()[4].schema(), other.nme_creator);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.nme_event_type)) {
        this.nme_event_type = data().deepCopy(fields()[5].schema(), other.nme_event_type);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing POCEntity instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kinsaleins.avro.POCEntity other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.idt_enterprise_txn_entity)) {
        this.idt_enterprise_txn_entity = data().deepCopy(fields()[0].schema(), other.idt_enterprise_txn_entity);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.num_enterprise_txn_entity_edition)) {
        this.num_enterprise_txn_entity_edition = data().deepCopy(fields()[1].schema(), other.num_enterprise_txn_entity_edition);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.num_enterprise_txn_entity_version)) {
        this.num_enterprise_txn_entity_version = data().deepCopy(fields()[2].schema(), other.num_enterprise_txn_entity_version);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dte_event_occurred)) {
        this.dte_event_occurred = data().deepCopy(fields()[3].schema(), other.dte_event_occurred);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.nme_creator)) {
        this.nme_creator = data().deepCopy(fields()[4].schema(), other.nme_creator);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.nme_event_type)) {
        this.nme_event_type = data().deepCopy(fields()[5].schema(), other.nme_event_type);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'idt_enterprise_txn_entity' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdtEnterpriseTxnEntity() {
      return idt_enterprise_txn_entity;
    }


    /**
      * Sets the value of the 'idt_enterprise_txn_entity' field.
      * @param value The value of 'idt_enterprise_txn_entity'.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder setIdtEnterpriseTxnEntity(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.idt_enterprise_txn_entity = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idt_enterprise_txn_entity' field has been set.
      * @return True if the 'idt_enterprise_txn_entity' field has been set, false otherwise.
      */
    public boolean hasIdtEnterpriseTxnEntity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idt_enterprise_txn_entity' field.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder clearIdtEnterpriseTxnEntity() {
      idt_enterprise_txn_entity = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_enterprise_txn_entity_edition' field.
      * @return The value.
      */
    public int getNumEnterpriseTxnEntityEdition() {
      return num_enterprise_txn_entity_edition;
    }


    /**
      * Sets the value of the 'num_enterprise_txn_entity_edition' field.
      * @param value The value of 'num_enterprise_txn_entity_edition'.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder setNumEnterpriseTxnEntityEdition(int value) {
      validate(fields()[1], value);
      this.num_enterprise_txn_entity_edition = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'num_enterprise_txn_entity_edition' field has been set.
      * @return True if the 'num_enterprise_txn_entity_edition' field has been set, false otherwise.
      */
    public boolean hasNumEnterpriseTxnEntityEdition() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'num_enterprise_txn_entity_edition' field.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder clearNumEnterpriseTxnEntityEdition() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_enterprise_txn_entity_version' field.
      * @return The value.
      */
    public int getNumEnterpriseTxnEntityVersion() {
      return num_enterprise_txn_entity_version;
    }


    /**
      * Sets the value of the 'num_enterprise_txn_entity_version' field.
      * @param value The value of 'num_enterprise_txn_entity_version'.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder setNumEnterpriseTxnEntityVersion(int value) {
      validate(fields()[2], value);
      this.num_enterprise_txn_entity_version = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'num_enterprise_txn_entity_version' field has been set.
      * @return True if the 'num_enterprise_txn_entity_version' field has been set, false otherwise.
      */
    public boolean hasNumEnterpriseTxnEntityVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'num_enterprise_txn_entity_version' field.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder clearNumEnterpriseTxnEntityVersion() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dte_event_occurred' field.
      * @return The value.
      */
    public java.lang.CharSequence getDteEventOccurred() {
      return dte_event_occurred;
    }


    /**
      * Sets the value of the 'dte_event_occurred' field.
      * @param value The value of 'dte_event_occurred'.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder setDteEventOccurred(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.dte_event_occurred = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dte_event_occurred' field has been set.
      * @return True if the 'dte_event_occurred' field has been set, false otherwise.
      */
    public boolean hasDteEventOccurred() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dte_event_occurred' field.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder clearDteEventOccurred() {
      dte_event_occurred = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'nme_creator' field.
      * @return The value.
      */
    public java.lang.CharSequence getNmeCreator() {
      return nme_creator;
    }


    /**
      * Sets the value of the 'nme_creator' field.
      * @param value The value of 'nme_creator'.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder setNmeCreator(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.nme_creator = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'nme_creator' field has been set.
      * @return True if the 'nme_creator' field has been set, false otherwise.
      */
    public boolean hasNmeCreator() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'nme_creator' field.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder clearNmeCreator() {
      nme_creator = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'nme_event_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getNmeEventType() {
      return nme_event_type;
    }


    /**
      * Sets the value of the 'nme_event_type' field.
      * @param value The value of 'nme_event_type'.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder setNmeEventType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.nme_event_type = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'nme_event_type' field has been set.
      * @return True if the 'nme_event_type' field has been set, false otherwise.
      */
    public boolean hasNmeEventType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'nme_event_type' field.
      * @return This builder.
      */
    public com.kinsaleins.avro.POCEntity.Builder clearNmeEventType() {
      nme_event_type = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public POCEntity build() {
      try {
        POCEntity record = new POCEntity();
        record.idt_enterprise_txn_entity = fieldSetFlags()[0] ? this.idt_enterprise_txn_entity : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.num_enterprise_txn_entity_edition = fieldSetFlags()[1] ? this.num_enterprise_txn_entity_edition : (java.lang.Integer) defaultValue(fields()[1]);
        record.num_enterprise_txn_entity_version = fieldSetFlags()[2] ? this.num_enterprise_txn_entity_version : (java.lang.Integer) defaultValue(fields()[2]);
        record.dte_event_occurred = fieldSetFlags()[3] ? this.dte_event_occurred : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.nme_creator = fieldSetFlags()[4] ? this.nme_creator : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.nme_event_type = fieldSetFlags()[5] ? this.nme_event_type : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<POCEntity>
    WRITER$ = (org.apache.avro.io.DatumWriter<POCEntity>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<POCEntity>
    READER$ = (org.apache.avro.io.DatumReader<POCEntity>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.idt_enterprise_txn_entity);

    out.writeInt(this.num_enterprise_txn_entity_edition);

    out.writeInt(this.num_enterprise_txn_entity_version);

    out.writeString(this.dte_event_occurred);

    out.writeString(this.nme_creator);

    out.writeString(this.nme_event_type);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idt_enterprise_txn_entity = in.readString(this.idt_enterprise_txn_entity instanceof Utf8 ? (Utf8)this.idt_enterprise_txn_entity : null);

      this.num_enterprise_txn_entity_edition = in.readInt();

      this.num_enterprise_txn_entity_version = in.readInt();

      this.dte_event_occurred = in.readString(this.dte_event_occurred instanceof Utf8 ? (Utf8)this.dte_event_occurred : null);

      this.nme_creator = in.readString(this.nme_creator instanceof Utf8 ? (Utf8)this.nme_creator : null);

      this.nme_event_type = in.readString(this.nme_event_type instanceof Utf8 ? (Utf8)this.nme_event_type : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idt_enterprise_txn_entity = in.readString(this.idt_enterprise_txn_entity instanceof Utf8 ? (Utf8)this.idt_enterprise_txn_entity : null);
          break;

        case 1:
          this.num_enterprise_txn_entity_edition = in.readInt();
          break;

        case 2:
          this.num_enterprise_txn_entity_version = in.readInt();
          break;

        case 3:
          this.dte_event_occurred = in.readString(this.dte_event_occurred instanceof Utf8 ? (Utf8)this.dte_event_occurred : null);
          break;

        case 4:
          this.nme_creator = in.readString(this.nme_creator instanceof Utf8 ? (Utf8)this.nme_creator : null);
          break;

        case 5:
          this.nme_event_type = in.readString(this.nme_event_type instanceof Utf8 ? (Utf8)this.nme_event_type : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










